/**
 * Download BrandLogo SVG assets from Brandfetch MCP signed URLs.
 *
 * 1. `get_brand` per domain → copy asset URL into `scripts/brand-logo-urls.json`
 * 2. `pnpm fetch:brands`
 */
import { existsSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { BRAND_CATALOG } from "../src/components/BrandLogo/brand-catalog.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SVG_DIR = path.resolve(__dirname, "../src/components/BrandLogo/svg");
const SVGS_PATH = path.resolve(
  __dirname,
  "../src/components/BrandLogo/brand-svgs.generated.ts",
);
const MANIFEST_PATH = path.resolve(__dirname, "brand-logo-urls.json");

function rasterToEmbeddedSvg(
  bytes: Buffer,
  mimeType: string,
  width: number,
  height: number,
): string {
  const base64 = bytes.toString("base64");
  return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><image width="${width}" height="${height}" href="data:${mimeType};base64,${base64}"/></svg>`;
}

async function downloadAsset(url: string): Promise<string> {
  const response = await fetch(url, { redirect: "follow" });
  if (!response.ok) {
    throw new Error(`HTTP ${response.status}`);
  }

  const contentType = response.headers.get("content-type") ?? "";
  const buffer = Buffer.from(await response.arrayBuffer());

  if (contentType.includes("svg")) {
    const text = buffer.toString("utf8");
    if (!text.includes("<svg")) {
      throw new Error("response is not SVG");
    }
    return text;
  }

  const mimeType = contentType.split(";")[0]?.trim() || "image/png";
  if (!mimeType.startsWith("image/")) {
    throw new Error(`unsupported content-type: ${contentType}`);
  }

  const wMatch = url.match(/\/w\/(\d+)\//);
  const hMatch = url.match(/\/h\/(\d+)\//);
  const width = Number(wMatch?.[1]) || 800;
  const height = Number(hMatch?.[1]) || 200;

  return rasterToEmbeddedSvg(buffer, mimeType, width, height);
}

function loadManifest(): Record<string, string> {
  if (!existsSync(MANIFEST_PATH)) {
    throw new Error(
      "Missing scripts/brand-logo-urls.json — populate via Brandfetch MCP get_brand.",
    );
  }

  const raw = JSON.parse(readFileSync(MANIFEST_PATH, "utf8")) as Record<
    string,
    string
  >;

  return Object.fromEntries(
    Object.entries(raw).filter(([key]) => !key.startsWith("_")),
  );
}

async function main() {
  const manifest = loadManifest();
  const missing = BRAND_CATALOG.filter((brand) => !manifest[brand.id]);
  if (missing.length > 0) {
    throw new Error(
      `Manifest missing URLs for: ${missing.map((b) => b.id).join(", ")}`,
    );
  }

  await mkdir(SVG_DIR, { recursive: true });

  const svgEntries: string[] = [];
  const failures: string[] = [];

  console.log("Downloading brand logos…\n");

  for (const brand of BRAND_CATALOG) {
    const url = manifest[brand.id];
    try {
      const svg = await downloadAsset(url);
      await writeFile(path.join(SVG_DIR, `${brand.id}.svg`), svg, "utf8");
      svgEntries.push(`  "${brand.id}": ${JSON.stringify(svg)},`);
      console.log(`✓ ${brand.id}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      failures.push(`${brand.id}: ${message}`);
      console.log(`✗ ${brand.id} — ${message}`);
    }
  }

  if (failures.length > 0) {
    throw new Error(
      `Failed to download ${failures.length} logo(s):\n${failures.join("\n")}`,
    );
  }

  await writeFile(
    SVGS_PATH,
    `/* AUTO-GENERATED by scripts/fetch-brand-logos.ts — do not edit */
import type { BrandId } from "./brand-catalog";

export const BRAND_SVGS: Record<BrandId, string> = {
${svgEntries.join("\n")}
};
`,
    "utf8",
  );

  console.log(`\n${BRAND_CATALOG.length} SVGs written.`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
